package org.hik.dtos.responses;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Map;

/**
 * The format used for events when they are returned from a homeserver to a client via the Client-Server API, or sent to an Application Service via the Application Services API.
 *
 * @param content        Required: The body of this event, as created by the client which sent it.
 * @param eventId        Required: The globally unique identifier for this event.
 * @param originServerTs Required: Timestamp (in milliseconds since the unix epoch) on originating homeserver when this event was sent.
 * @param roomId         Required: The ID of the room associated with this event.
 * @param sender         Required: Contains the fully-qualified ID of the user who sent this event.
 * @param stateKey       Present if, and only if, this event is a state event. The key making this piece of state unique in the room. Note that it is often an empty string.
 *                       <p>
 *                       State keys starting with an @ are reserved for referencing user IDs, such as room members. Except a few events, state events set with a given user’s ID as the state key MUST only be set by that user.
 * @param type           Required: The type of the event.
 * @param unsigned       Contains optional extra information about the event.
 */
public record ClientEvent(Map<String, Object> content,
                          @JsonProperty("event_id") String eventId,
                          @JsonProperty("origin_server_ts") Long originServerTs,
                          @JsonProperty("room_id") String roomId,
                          String sender,
                          @JsonProperty("state_key") String stateKey,
                          String type,
                          UnsignedData unsigned
) {
    /**
     *
     * @param age             The time in milliseconds that has elapsed since the event was sent. Generated by the local homeserver, and may be incorrect if the servers is out of sync.
     *                        which can cause the age to either be negative or greater than it actually is.
     * @param membership      The room membership of the user making the request, at the time of the event. More information in the official documents
     * @param redactedBecause The event that redacted this event, if any.
     * @param transactionId   The client-supplied transaction ID, for example, provided via PUT /_matrix/client/v3/rooms/{roomId}/send/{eventType}/{txnId}, if the client being given the event is the same one which sent it.
     * @apiNote the object that is part of prev_content is not yet implement here
     */
    public record UnsignedData(Long age,
                               String membership,
                               @JsonProperty("redacted_because") ClientEvent redactedBecause,
                               @JsonProperty("transaction_id") String transactionId) {
    }
}
