package org.hik.api.events;

import java.util.Map;

/// The record used for events when they are returned from a homeserver to a client via the Client-Server API, or
/// sent to an Application Service via the Application Services API.
///
/// @param content        the body of this event, as created by the client which sent it.
/// @param eventId        the globally unique identifier for this event.
/// @param originServerTs timestamp (in milliseconds since the Unix epoch) on originating homeserver when this event
/// was sent.
/// @param roomId         the ID of the room associated with this event.
/// @param sender         contains the fully-qualified ID of the user who sent this event.
/// @param stateKey       present if, and only if, this event is a state event. The key making this piece of state
/// unique in the room. Note that it is often an empty string.
///
/// State keys starting with an @ are reserved for referencing user IDs, such as room members. Except a few events,
/// state events set with a given user’s ID as the state key MUST only be set by that user.
/// @param type           the type of the event.
/// @param unsigned       contains optional extra information about the event.
public record ClientEvent(Map<String, Object> content,
                          String eventId,
                          Long originServerTs,
                          String roomId,
                          String sender,
                          String stateKey,
                          String type,
                          UnsignedData unsigned
) {
    /// Contains extra information about the event.
    ///
    /// @param age             the time in milliseconds that has elapsed since the event was sent. Generated by the
    /// local homeserver, and may be incorrect if the servers is out of sync.
    ///                        which can cause the age to either be negative or greater than it actually is.
    /// @param membership      the room membership of the user making the request, at the time of the event. More
    /// information in the specification.
    /// @param redactedBecause the event that redacted this event, if any.
    /// @param transactionId   the client-supplied transaction ID, for example, provided via `PUT /_matrix/client/v3
    /// /rooms/{roomId}/send/{eventType}/{txnId}`, if the client being given the event is the same one which sent it.
    public record UnsignedData(Long age,
                               String membership,
                               ClientEvent redactedBecause,
                               String transactionId) {
    }
}
