package org.hik.api.events;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Map;


/// Represents the format used for event retrieval.
///
/// @param content        the body of this event, as created by the user which sent it.
/// @param eventId        the globally unique identifier for this event.
/// @param originServerTs timestamp (in milliseconds since the Unix epoch) on originating homeserver when this event
/// was sent.
/// @param roomId         the ID of the room associated with this event.
/// @param sender         contains the fully-qualified ID of the user who sent this event.
/// @param stateKey       present if, and only if, this event is a state event. The key making this piece of state
/// unique in the room. Note that it is often an empty string.
///
/// State keys starting with an @ are reserved for referencing user IDs, such as room members. Except a few events,
/// state events set with a given user’s ID as the state key MUST only be set by that user.
/// @param type           the type of the event.
/// @param unsigned       contains optional extra information about the event.
/// @see <a href="https://spec.matrix.org/latest/client-server-api/#room-event-format">The room event format as defined in the specification.</a>
public record ClientEvent(@JsonProperty(required = true) Map<String, Object> content,
                          @JsonProperty(required = true) String eventId,
                          @JsonProperty(required = true) Long originServerTs,
                          @JsonProperty(required = true) String roomId,
                          @JsonProperty(required = true) String sender,
                          String stateKey,
                          @JsonProperty(required = true) String type,
                          UnsignedData unsigned
) {
    /// Additional information about the event.
    ///
    /// @param age             the time in milliseconds that has elapsed since the event was sent. Generated by the
    /// local homeserver, and may be incorrect if the servers is out of sync.
    ///                        which can cause the age to either be negative or greater than it actually is.
    /// @param membership      the room membership of the user making the request, at the time of the event. More
    /// information in the specification.
    /// @param prev_content    the `content` of the previous state event that was replaced by this event. This field is generated by the local homeserver, and is only returned if the event is a state event, and the client has permission to see the previous event.
    /// @param redactedBecause the event that redacted this event, if any.
    /// @param replacesState   the Event ID of the state event replaced by this event. This field is generated by the local homeserver, and is only returned if the event is a state event. Unlike `prev_content`, this field is included regardless of history visibility.
    /// @param transactionId   the client-supplied transaction ID, for example, provided via `PUT /_matrix/client/v3
    /// /rooms/{roomId}/send/{eventType}/{txnId}`, if the client being given the event is the same one which sent it.
    public record UnsignedData(Long age,
                               String membership,
                               EventContent prev_content,
                               ClientEvent redactedBecause,
                               String replacesState,
                               String transactionId) {
    }
}
